import { BuildingsColorEnum, DicePointsEnum, PlayerTerritoryType, StateEnum } from "./utils";

const playersTerritoryList1: PlayerTerritoryType[] = [
  //
  {
    x: 0,
    y: 0,
    background: BuildingsColorEnum.GREEN,
    pointNum: DicePointsEnum.SIX,
    building: StateEnum.EMPTY,
  },
  {
    x: 1,
    y: 0,
    background: BuildingsColorEnum.DARK_GREEN,
    pointNum: DicePointsEnum.FIVE,
    building: StateEnum.EMPTY,
  },
  {
    x: 2,
    y: 0,
    background: BuildingsColorEnum.DARK_GREEN,
    pointNum: DicePointsEnum.FOUR,
    building: StateEnum.EMPTY,
  },
  {
    x: 3,
    y: 0,
    background: BuildingsColorEnum.YELLOW,
    pointNum: DicePointsEnum.THREE,
    building: StateEnum.EMPTY,
  },
  //
  {
    x: 0,
    y: 1,
    background: BuildingsColorEnum.GREEN,
    pointNum: DicePointsEnum.TWO,
    building: StateEnum.EMPTY,
  },
  {
    x: 1,
    y: 1,
    background: BuildingsColorEnum.GREEN,
    pointNum: DicePointsEnum.ONE,
    building: StateEnum.EMPTY,
  },
  {
    x: 2,
    y: 1,
    background: BuildingsColorEnum.DARK_GREEN,
    pointNum: DicePointsEnum.SIX,
    building: StateEnum.EMPTY,
  },
  {
    x: 3,
    y: 1,
    background: BuildingsColorEnum.YELLOW,
    pointNum: DicePointsEnum.FIVE,
    building: StateEnum.EMPTY,
  },
  {
    x: 4,
    y: 1,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.FOUR,
    building: StateEnum.EMPTY,
  },
  {
    x: -1,
    y: 2,
    background: BuildingsColorEnum.GREEN,
    pointNum: DicePointsEnum.FIVE,
    building: StateEnum.EMPTY,
  },
  {
    x: 0,
    y: 2,
    background: BuildingsColorEnum.GREEN,
    pointNum: DicePointsEnum.FOUR,
    building: StateEnum.EMPTY,
  },
  {
    x: 1,
    y: 2,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.THREE,
    building: StateEnum.EMPTY,
  },
  {
    x: 2,
    y: 2,
    background: BuildingsColorEnum.YELLOW,
    pointNum: DicePointsEnum.ONE,
    building: StateEnum.EMPTY,
  },
  {
    x: 3,
    y: 2,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.TWO,
    building: StateEnum.EMPTY,
  },
  {
    x: 4,
    y: 2,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.THREE,
    building: StateEnum.EMPTY,
  },
  //
  {
    x: -1,
    y: 3,
    background: BuildingsColorEnum.BLUE,
    pointNum: DicePointsEnum.SIX,
    building: StateEnum.EMPTY,
  },
  {
    x: 0,
    y: 3,
    background: BuildingsColorEnum.BLUE,
    pointNum: DicePointsEnum.ONE,
    building: StateEnum.EMPTY,
  },
  {
    x: 1,
    y: 3,
    background: BuildingsColorEnum.BLUE,
    pointNum: DicePointsEnum.TWO,
    building: StateEnum.EMPTY,
  },
  {
    x: 2,
    y: 3,
    background: BuildingsColorEnum.DARK_GREEN,
    pointNum: DicePointsEnum.SIX,
    building: StateEnum.EMPTY,
  },
  {
    x: 3,
    y: 3,
    background: BuildingsColorEnum.BLUE,
    pointNum: DicePointsEnum.FIVE,
    building: StateEnum.EMPTY,
  },
  {
    x: 4,
    y: 3,
    background: BuildingsColorEnum.BLUE,
    pointNum: DicePointsEnum.FOUR,
    building: StateEnum.EMPTY,
  },
  {
    x: 5,
    y: 3,
    background: BuildingsColorEnum.BLUE,
    pointNum: DicePointsEnum.ONE,
    building: StateEnum.EMPTY,
  },
  //
  {
    x: -1,
    y: 4,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.TWO,
    building: StateEnum.EMPTY,
  },
  {
    x: 0,
    y: 4,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.FIVE,
    building: StateEnum.EMPTY,
  },
  {
    x: 1,
    y: 4,
    background: BuildingsColorEnum.GREY,
    pointNum: DicePointsEnum.FOUR,
    building: StateEnum.EMPTY,
  },
  {
    x: 2,
    y: 4,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.THREE,
    building: StateEnum.EMPTY,
  },
  {
    x: 3,
    y: 4,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.ONE,
    building: StateEnum.EMPTY,
  },
  {
    x: 4,
    y: 4,
    background: BuildingsColorEnum.GREEN,
    pointNum: DicePointsEnum.TWO,
    building: StateEnum.EMPTY,
  },
  //
  {
    x: 0,
    y: 5,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.SIX,
    building: StateEnum.EMPTY,
  },
  {
    x: 1,
    y: 5,
    background: BuildingsColorEnum.GREY,
    pointNum: DicePointsEnum.ONE,
    building: StateEnum.EMPTY,
  },
  {
    x: 2,
    y: 5,
    background: BuildingsColorEnum.YELLOW,
    pointNum: DicePointsEnum.TWO,
    building: StateEnum.EMPTY,
  },
  {
    x: 3,
    y: 5,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.FIVE,
    building: StateEnum.EMPTY,
  },
  {
    x: 4,
    y: 5,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.SIX,
    building: StateEnum.EMPTY,
  },
  //
  {
    x: 0,
    y: 6,
    background: BuildingsColorEnum.GREEN,
    pointNum: DicePointsEnum.THREE,
    building: StateEnum.EMPTY,
  },
  {
    x: 1,
    y: 6,
    background: BuildingsColorEnum.YELLOW,
    pointNum: DicePointsEnum.FOUR,
    building: StateEnum.EMPTY,
  },
  {
    x: 2,
    y: 6,
    background: BuildingsColorEnum.YELLOW,
    pointNum: DicePointsEnum.ONE,
    building: StateEnum.EMPTY,
  },
  {
    x: 3,
    y: 6,
    background: BuildingsColorEnum.BROWN,
    pointNum: DicePointsEnum.THREE,
    building: StateEnum.EMPTY,
  },
];

export const playersTerritoryList: PlayerTerritoryType[][] = [playersTerritoryList1];
